import { GetServerSideProps } from "next";
import Head from "next/head";

type Home = {
  count: number;
};

export default function Home({ count }: Home) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Oi {count}</h1>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Home> = async () => {
  const response = await (
    await fetch("http://localhost:3333/pools/count")
  ).json();

  return {
    props: { count: response?.count },
  };
};
